// docs/src/theme/Footer/index.tsx
import React from 'react';
import useBaseUrl from '@docusaurus/useBaseUrl';

type LinkItem = {label: string; href: string};

const groups: {title: string; items: LinkItem[]}[] = [
  {
    title: 'Project',
    items: [
      {label: 'GitHub', href: 'https://github.com/openkaiden/kaiden'},
      {label: 'Releases', href: 'https://github.com/openkaiden/kaiden/releases'},
      {label: 'kdn CLI', href: 'https://github.com/openkaiden/kdn'},
      {label: 'MCP Registry', href: 'https://github.com/openkaiden/mcp-registry-online'},
    ],
  },
  {
    title: 'Organization',
    items: [
      {label: 'openkaiden', href: 'https://github.com/openkaiden'},
      {label: 'License (Apache 2.0)', href: 'https://github.com/openkaiden/kaiden/blob/main/LICENSE'},
      {label: 'llms.txt', href: '/llms.txt'},
    ],
  },
];

export default function Footer(): React.ReactElement {
  const iconUrl = useBaseUrl('/img/icon.png');
  return (
    <footer className="kaiden-footer">
      <div className="kaiden-footer__inner">
        <div className="kaiden-footer__brand">
          <a href="/" className="kaiden-footer__logo-link">
            <img src={iconUrl} alt="Kaiden" width={28} height={28} className="kaiden-footer__icon" />
            <span className="kaiden-footer__name">kaiden</span>
          </a>
          <p className="kaiden-footer__desc">
            Open platform for running AI coding agents in isolated sandboxes with enterprise-grade governance.
          </p>
          <p className="kaiden-footer__license">Apache 2.0 · openkaiden organization</p>
        </div>

        {groups.map((group) => (
          <div key={group.title} className="kaiden-footer__group">
            <p className="kaiden-footer__group-title">{group.title}</p>
            <ul className="kaiden-footer__links">
              {group.items.map((item) => (
                <li key={item.label}>
                  <a
                    href={item.href}
                    className="kaiden-footer__link"
                    target={item.href.startsWith('http') ? '_blank' : undefined}
                    rel={item.href.startsWith('http') ? 'noopener noreferrer' : undefined}
                  >
                    {item.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </footer>
  );
}

// src/lib/components/Footer.svelte
<script lang="ts">
  import { assets, base } from '$app/paths';
  const links = [
    {
      group: 'Project',
      items: [
        { label: 'GitHub', href: 'https://github.com/openkaiden/kaiden' },
        { label: 'Releases', href: 'https://github.com/openkaiden/kaiden/releases' },
        { label: 'kdn CLI', href: 'https://github.com/openkaiden/kdn' },
        { label: 'MCP Registry', href: 'https://github.com/openkaiden/mcp-registry-online' }
      ]
    },
    {
      group: 'Organization',
      items: [
        { label: 'openkaiden', href: 'https://github.com/openkaiden' },
        { label: 'License (Apache 2.0)', href: 'https://github.com/openkaiden/kaiden/blob/main/LICENSE' },
        { label: 'llms.txt', href: `${base}/llms.txt` }
      ]
    }
  ];
</script>

<footer class="border-t" style="border-color: var(--border); background: var(--bg-card)">
  <div class="max-w-6xl mx-auto px-6 py-16">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-10">

      <!-- brand -->
      <div>
        <div class="flex items-center gap-2.5 mb-4">
          <img src="{assets}/icon.png" alt="Kaiden" width="28" height="28" style="border-radius: 22%; box-shadow: 0 2px 8px rgba(0,0,0,0.18)" />
          <span class="font-semibold tracking-tight" style="color: var(--text-primary)">kaiden</span>
        </div>
        <p class="text-sm leading-relaxed max-w-xs" style="color: var(--text-muted)">
          Open platform for running AI coding agents in isolated sandboxes with enterprise-grade governance.
        </p>
        <p class="mt-4 text-xs" style="color: var(--text-muted)">Apache 2.0 &middot; openkaiden organization</p>
      </div>

      <!-- link columns -->
      {#each links as group}
        <div>
          <p class="text-[11px] font-mono uppercase tracking-widest mb-4" style="color: var(--text-muted)">{group.group}</p>
          <ul class="space-y-2.5">
            {#each group.items as item}
              <li>
                <a
                  href={item.href}
                  target={item.href.startsWith('http') ? '_blank' : undefined}
                  rel={item.href.startsWith('http') ? 'noopener noreferrer' : undefined}
                  class="text-sm transition-colors hover:opacity-80"
                  style="color: var(--text-secondary)"
                >{item.label}</a>
              </li>
            {/each}
          </ul>
        </div>
      {/each}

    </div>
  </div>
</footer>
